import React, { useState, useRef, useEffect } from "react"
import { generateQRCode } from "../../api/qrCode"
import BrandedQRCode from "./BrandedQRCode"
import {
    FiDownload,
    FiCopy,
    FiX,
    FiCheckCircle,
    FiAlertCircle,
    FiShare2,
    FiLock,
    FiClock,
    FiEye
} from "react-icons/fi"
import { AiOutlineLoading3Quarters } from "react-icons/ai"
import { MdQrCode2 } from "react-icons/md"
import "./BeautifulQRDialog.css"

const BeautifulQRDialog = ({
    isOpen,
    onClose,
    patientId,
    patientName,
    onGenerate = null
}) => {
    const qrRef = useRef(null)
    const [loading, setLoading] = useState(false)
    const [error, setError] = useState(null)
    const [generatedQR, setGeneratedQR] = useState(null)
    const [copied, setCopied] = useState(false)
    const [autoGenerated, setAutoGenerated] = useState(false)

    // Auto-generate when dialog opens
    useEffect(() => {
        if (isOpen && !autoGenerated && patientId) {
            handleGenerate()
            setAutoGenerated(true)
        }
        if (!isOpen) {
            setAutoGenerated(false)
            setGeneratedQR(null)
            setError(null)
        }
    }, [isOpen, patientId])

    const handleGenerate = async () => {
        setLoading(true)
        setError(null)

        try {
            const qrData = {
                patient_id: patientId,
                share_type: "parent_access",
                expires_in_days: 30,
                scope: ["view_only", "allergies", "vaccinations", "appointments"],
                max_uses: 100,
                allow_emergency_access: false,
                metadata: {
                    shared_by: "parent",
                    patient_name: patientName
                }
            }

            const response = await generateQRCode(qrData)

            if (!response || !response.token || !response.access_url) {
                throw new Error("Invalid response from server. Please try again.")
            }

            setGeneratedQR({
                qrId: response.qr_id,
                token: response.token,
                accessUrl: response.access_url,
                expiresAt: response.expires_at
            })

            if (onGenerate) {
                onGenerate(response)
            }
        } catch (err) {
            console.error("QR Generation Error:", err)
            let errorMessage = "Failed to generate QR code. Please try again."

            if (err.message) {
                if (err.message.includes("Patient not found")) {
                    errorMessage = "Patient record not found. Please contact support."
                } else if (err.message.includes("permission")) {
                    errorMessage = "You don't have permission to generate QR codes for this patient."
                } else if (err.message.includes("network") || err.message.includes("internet")) {
                    errorMessage = "Network error. Please check your connection and try again."
                } else if (err.message.includes("Server error")) {
                    errorMessage = err.message // Show full server error for debugging
                } else {
                    errorMessage = err.message
                }
            }

            setError(errorMessage)
        } finally {
            setLoading(false)
        }
    }

    const handleDownload = async () => {
        if (!qrRef.current) return

        try {
            const canvas = document.createElement("canvas")
            const ctx = canvas.getContext("2d")

            const size = 600
            canvas.width = size
            canvas.height = size + 200

            // Gradient background - using KEEPSAKE primary colors
            const gradient = ctx.createLinearGradient(0, 0, size, size + 200)
            gradient.addColorStop(0, "rgb(59, 130, 246)") // Primary blue
            gradient.addColorStop(0.5, "rgb(96, 165, 250)") // Accent light blue
            gradient.addColorStop(1, "rgb(147, 197, 253)") // Light blue
            ctx.fillStyle = gradient
            ctx.fillRect(0, 0, canvas.width, canvas.height)

            // Semi-transparent overlay
            ctx.fillStyle = "rgba(255, 255, 255, 0.95)"
            ctx.fillRect(20, 20, size - 40, size + 160)

            // Patient name
            ctx.fillStyle = "#1f2937"
            ctx.font = "bold 32px Arial"
            ctx.textAlign = "center"
            ctx.fillText(patientName || "Patient QR Code", size / 2, 80)

            // KEEPSAKE branding
            ctx.font = "20px Arial"
            ctx.fillStyle = "#6b7280"
            ctx.fillText("KEEPSAKE Healthcare", size / 2, 115)

            // Capture QR code
            const svgElements = qrRef.current.querySelectorAll("svg")
            const imgElement = qrRef.current.querySelector("img")

            if (svgElements.length > 0) {
                const qrSvg = svgElements[0]
                const svgData = new XMLSerializer().serializeToString(qrSvg)
                const svgBlob = new Blob([svgData], { type: "image/svg+xml;charset=utf-8" })
                const url = URL.createObjectURL(svgBlob)

                const qrImg = new Image()

                await new Promise((resolve, reject) => {
                    qrImg.onload = async () => {
                        // Draw QR code with white background
                        const qrSize = 380
                        const x = (size - qrSize) / 2
                        const y = 150

                        // White background for QR
                        ctx.fillStyle = "#ffffff"
                        ctx.shadowColor = "rgba(0, 0, 0, 0.1)"
                        ctx.shadowBlur = 20
                        ctx.fillRect(x - 15, y - 15, qrSize + 30, qrSize + 30)
                        ctx.shadowBlur = 0

                        ctx.drawImage(qrImg, x, y, qrSize, qrSize)

                        // Overlay logo
                        if (imgElement && imgElement.complete) {
                            const logoSize = 85
                            const logoX = size / 2 - logoSize / 2
                            const logoY = y + qrSize / 2 - logoSize / 2

                            ctx.fillStyle = "#ffffff"
                            ctx.beginPath()
                            ctx.roundRect(logoX - 8, logoY - 8, logoSize + 16, logoSize + 16, 12)
                            ctx.fill()

                            try {
                                ctx.drawImage(imgElement, logoX, logoY, logoSize, logoSize)
                            } catch (logoErr) {
                                console.warn("Could not draw logo:", logoErr)
                            }
                        }

                        // Footer info
                        ctx.fillStyle = "#4b5563"
                        ctx.font = "16px Arial"
                        const expiryDate = new Date(generatedQR.expiresAt).toLocaleDateString("en-US", {
                            year: "numeric",
                            month: "long",
                            day: "numeric"
                        })
                        ctx.fillText(`Valid until ${expiryDate}`, size / 2, y + qrSize + 60)

                        ctx.font = "14px Arial"
                        ctx.fillStyle = "#9ca3af"
                        ctx.fillText("Scan to access medical records securely", size / 2, y + qrSize + 90)

                        URL.revokeObjectURL(url)
                        resolve()
                    }
                    qrImg.onerror = reject
                    qrImg.src = url
                })

                const pngFile = canvas.toDataURL("image/png", 1.0)
                const downloadLink = document.createElement("a")
                downloadLink.download = `${patientName?.replace(/\s+/g, "_")}_KEEPSAKE_QR.png`
                downloadLink.href = pngFile
                downloadLink.click()
            }
        } catch (err) {
            console.error("Download failed:", err)
            alert("Failed to download QR code. Please try again.")
        }
    }

    const handleCopyUrl = async () => {
        if (!generatedQR?.accessUrl) return

        try {
            await navigator.clipboard.writeText(generatedQR.accessUrl)
            setCopied(true)
            setTimeout(() => setCopied(false), 2000)
        } catch {
            const textArea = document.createElement("textarea")
            textArea.value = generatedQR.accessUrl
            document.body.appendChild(textArea)
            textArea.select()
            document.execCommand("copy")
            document.body.removeChild(textArea)
            setCopied(true)
            setTimeout(() => setCopied(false), 2000)
        }
    }

    const formatExpiryDate = (dateString) => {
        if (!dateString) return "N/A"
        try {
            return new Date(dateString).toLocaleDateString("en-US", {
                year: "numeric",
                month: "long",
                day: "numeric"
            })
        } catch {
            return dateString
        }
    }

    if (!isOpen) return null

    return (
        <div className="beautiful-qr-overlay" onClick={onClose}>
            <div className="beautiful-qr-dialog" onClick={(e) => e.stopPropagation()}>
                {/* Close button */}
                <button className="beautiful-qr-close" onClick={onClose} aria-label="Close">
                    <FiX />
                </button>

                {/* Header */}
                <div className="beautiful-qr-header">
                    <div className="beautiful-qr-icon">
                        <MdQrCode2 />
                    </div>
                    <h2 className="beautiful-qr-title">Share Medical Records</h2>
                    <p className="beautiful-qr-subtitle">
                        Secure QR code for {patientName}
                    </p>
                </div>

                {/* Content */}
                <div className="beautiful-qr-content">
                    {loading ? (
                        <div className="beautiful-qr-loading">
                            <AiOutlineLoading3Quarters className="beautiful-qr-spinner" />
                            <span>Generating secure QR code...</span>
                        </div>
                    ) : error ? (
                        <div className="beautiful-qr-error">
                            <FiAlertCircle className="beautiful-qr-error-icon" />
                            <h3>Oops! Something went wrong</h3>
                            <p>{error}</p>
                            <button className="beautiful-qr-retry-btn" onClick={handleGenerate}>
                                Try Again
                            </button>
                        </div>
                    ) : generatedQR ? (
                        <>
                            {/* QR Code Display */}
                            <div className="beautiful-qr-display">
                                <div ref={qrRef} className="beautiful-qr-code-container">
                                    <BrandedQRCode
                                        value={generatedQR.accessUrl}
                                        size={280}
                                        level="H"
                                        logoSize={65}
                                    />
                                </div>
                                <div className="beautiful-qr-success">
                                    <FiCheckCircle />
                                    <span>Ready to share!</span>
                                </div>
                            </div>

                            {/* Info Cards */}
                            <div className="beautiful-qr-info-grid">
                                <div className="beautiful-qr-info-card">
                                    <FiLock className="beautiful-qr-info-icon" />
                                    <div>
                                        <div className="beautiful-qr-info-label">Security</div>
                                        <div className="beautiful-qr-info-value">Encrypted</div>
                                    </div>
                                </div>
                                <div className="beautiful-qr-info-card">
                                    <FiClock className="beautiful-qr-info-icon" />
                                    <div>
                                        <div className="beautiful-qr-info-label">Valid Until</div>
                                        <div className="beautiful-qr-info-value">
                                            {new Date(generatedQR.expiresAt).toLocaleDateString("en-US", {
                                                month: "short",
                                                day: "numeric"
                                            })}
                                        </div>
                                    </div>
                                </div>
                                <div className="beautiful-qr-info-card">
                                    <FiEye className="beautiful-qr-info-icon" />
                                    <div>
                                        <div className="beautiful-qr-info-label">Access</div>
                                        <div className="beautiful-qr-info-value">View Only</div>
                                    </div>
                                </div>
                            </div>

                            {/* Instructions */}
                            <div className="beautiful-qr-instructions">
                                <p>
                                    <strong>How to use:</strong> Healthcare providers can scan this QR code
                                    to securely access {patientName}'s medical information including allergies,
                                    vaccinations, and appointments.
                                </p>
                            </div>

                            {/* Action Buttons */}
                            <div className="beautiful-qr-actions">
                                <button
                                    className="beautiful-qr-btn beautiful-qr-btn-primary"
                                    onClick={handleDownload}
                                >
                                    <FiDownload />
                                    <span>Download QR Code</span>
                                </button>
                                <button
                                    className="beautiful-qr-btn beautiful-qr-btn-secondary"
                                    onClick={handleCopyUrl}
                                >
                                    {copied ? (
                                        <>
                                            <FiCheckCircle />
                                            <span>Copied!</span>
                                        </>
                                    ) : (
                                        <>
                                            <FiCopy />
                                            <span>Copy Link</span>
                                        </>
                                    )}
                                </button>
                            </div>
                        </>
                    ) : null}
                </div>
            </div>
        </div>
    )
}

export default BeautifulQRDialog
