import React, { useState, useRef } from "react"
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogDescription,
} from "../ui/dialog"
import { Button } from "../ui/Button"
import BrandedQRCode from "./BrandedQRCode"
import { generateQRCode } from "../../api/qrCode"
import {
    FiDownload,
    FiCopy,
    FiCheckCircle,
    FiAlertCircle,
    FiUsers
} from "react-icons/fi"
import { MdQrCode2 } from "react-icons/md"
import { AiOutlineLoading3Quarters } from "react-icons/ai"

/**
 * DoctorParentQRShareDialog - Dialog for doctors to generate QR codes for parent access
 *
 * When a parent scans this QR code, they will gain access to the child's records.
 * Uses simple defaults: 7-day expiry, standard parent scope, no PIN.
 */
const DoctorParentQRShareDialog = ({
    isOpen,
    onClose,
    patientId,
    patientName,
    onGenerate = null
}) => {
    const qrRef = useRef(null)
    const [loading, setLoading] = useState(false)
    const [error, setError] = useState(null)
    const [generatedQR, setGeneratedQR] = useState(null)
    const [copied, setCopied] = useState(false)
    const [autoGenerated, setAutoGenerated] = useState(false)

    // Auto-generate when dialog opens
    React.useEffect(() => {
        if (isOpen && !autoGenerated && patientId) {
            handleGenerate()
            setAutoGenerated(true)
        }
        if (!isOpen) {
            setAutoGenerated(false)
            setGeneratedQR(null)
            setError(null)
        }
    }, [isOpen, patientId])

    const handleGenerate = async () => {
        setLoading(true)
        setError(null)

        try {
            const qrData = {
                patient_id: patientId,
                share_type: "parent_access_grant", // Special type for granting parent access
                expires_in_days: 7, // 7-day expiry as per requirements
                scope: ["view_only", "allergies", "vaccinations", "appointments"],
                max_uses: 1, // One-time use for parent registration
                allow_emergency_access: false,
                metadata: {
                    shared_by: "doctor",
                    patient_name: patientName,
                    purpose: "parent_access_grant"
                }
            }

            const response = await generateQRCode(qrData)

            // Validate response
            if (!response || !response.token || !response.access_url) {
                throw new Error("Invalid response from server. Please try again.")
            }

            setGeneratedQR({
                qrId: response.qr_id,
                token: response.token,
                accessUrl: response.access_url,
                expiresAt: response.expires_at
            })

            if (onGenerate) {
                onGenerate(response)
            }
        } catch (err) {
            console.error("QR Generation Error:", err)
            let errorMessage = "Failed to generate QR code. Please try again."

            if (err.message) {
                if (err.message.includes("Patient not found")) {
                    errorMessage = "Patient record not found. Please contact support."
                } else if (err.message.includes("permission")) {
                    errorMessage = "You don't have permission to generate QR codes for this patient."
                } else if (err.message.includes("network") || err.message.includes("internet")) {
                    errorMessage = "Network error. Please check your connection and try again."
                } else if (err.message.includes("Server error")) {
                    errorMessage = "Server is experiencing issues. Please try again in a moment."
                } else {
                    errorMessage = err.message
                }
            }

            setError(errorMessage)
        } finally {
            setLoading(false)
        }
    }

    const handleDownload = async () => {
        if (!qrRef.current) return

        try {
            const canvas = document.createElement("canvas")
            const ctx = canvas.getContext("2d")

            const size = 500
            canvas.width = size
            canvas.height = size + 150

            // White background
            ctx.fillStyle = "#ffffff"
            ctx.fillRect(0, 0, canvas.width, canvas.height)

            // Add gradient header background (green for parent access)
            const gradient = ctx.createLinearGradient(0, 0, size, 0)
            gradient.addColorStop(0, "#10b981") // emerald-500
            gradient.addColorStop(1, "#059669") // emerald-600
            ctx.fillStyle = gradient
            ctx.fillRect(0, 0, size, 80)

            // Patient name at top (white text on gradient)
            ctx.fillStyle = "#ffffff"
            ctx.font = "bold 24px Arial"
            ctx.textAlign = "center"
            ctx.fillText(`Parent Access: ${patientName || "Patient"}`, size / 2, 35)

            // Subtitle
            ctx.font = "16px Arial"
            ctx.fillText("KEEPSAKE Healthcare", size / 2, 60)

            // Capture the QR code
            const qrContainer = qrRef.current
            const svgElements = qrContainer.querySelectorAll("svg")
            const imgElement = qrContainer.querySelector("img")

            if (svgElements.length > 0) {
                const qrSvg = svgElements[0]
                const svgData = new XMLSerializer().serializeToString(qrSvg)
                const svgBlob = new Blob([svgData], { type: "image/svg+xml;charset=utf-8" })
                const url = URL.createObjectURL(svgBlob)

                const qrImg = new Image()

                await new Promise((resolve, reject) => {
                    qrImg.onload = async () => {
                        const qrSize = 350
                        const x = (size - qrSize) / 2
                        const y = 100

                        ctx.drawImage(qrImg, x, y, qrSize, qrSize)

                        // Overlay the logo if it exists
                        if (imgElement && imgElement.complete) {
                            const logoSize = 70
                            const logoX = size / 2 - logoSize / 2
                            const logoY = y + qrSize / 2 - logoSize / 2

                            ctx.fillStyle = "#ffffff"
                            ctx.beginPath()
                            ctx.roundRect(logoX - 5, logoY - 5, logoSize + 10, logoSize + 10, 8)
                            ctx.fill()
                            ctx.strokeStyle = "#e5e7eb"
                            ctx.lineWidth = 2
                            ctx.stroke()

                            try {
                                ctx.drawImage(imgElement, logoX, logoY, logoSize, logoSize)
                            } catch (logoErr) {
                                console.warn("Could not draw logo:", logoErr)
                            }
                        }

                        // Footer info
                        ctx.fillStyle = "#6b7280"
                        ctx.font = "14px Arial"
                        const expiryDate = new Date(generatedQR.expiresAt).toLocaleDateString("en-US", {
                            year: "numeric",
                            month: "long",
                            day: "numeric"
                        })
                        ctx.fillText(`Valid until: ${expiryDate}`, size / 2, size + 100)

                        ctx.font = "12px Arial"
                        ctx.fillStyle = "#9ca3af"
                        ctx.fillText("Scan to gain access to your child's records", size / 2, size + 130)

                        URL.revokeObjectURL(url)
                        resolve()
                    }
                    qrImg.onerror = reject
                    qrImg.src = url
                })

                const pngFile = canvas.toDataURL("image/png", 1.0)
                const downloadLink = document.createElement("a")
                downloadLink.download = `${patientName?.replace(/\s+/g, "_")}_Parent_Access_QR.png`
                downloadLink.href = pngFile
                downloadLink.click()
            }
        } catch (err) {
            console.error("Download failed:", err)
            alert("Failed to download QR code. Please try again.")
        }
    }

    const handleCopyUrl = async () => {
        if (!generatedQR?.accessUrl) return

        try {
            await navigator.clipboard.writeText(generatedQR.accessUrl)
            setCopied(true)
            setTimeout(() => setCopied(false), 2000)
        } catch {
            const textArea = document.createElement("textarea")
            textArea.value = generatedQR.accessUrl
            document.body.appendChild(textArea)
            textArea.select()
            document.execCommand("copy")
            document.body.removeChild(textArea)
            setCopied(true)
            setTimeout(() => setCopied(false), 2000)
        }
    }

    const formatExpiryDate = (dateString) => {
        if (!dateString) return "N/A"
        try {
            return new Date(dateString).toLocaleDateString("en-US", {
                year: "numeric",
                month: "long",
                day: "numeric"
            })
        } catch {
            return dateString
        }
    }

    return (
        <Dialog open={isOpen} onOpenChange={onClose}>
            <DialogContent className="sm:max-w-md">
                <DialogHeader>
                    <div className="flex items-center gap-2">
                        <div className="p-2 bg-gradient-to-br from-emerald-100 to-green-100 rounded-full">
                            <FiUsers className="text-2xl text-emerald-600" />
                        </div>
                        <div>
                            <DialogTitle>Share with Parent</DialogTitle>
                            <DialogDescription className="mt-1">
                                Generate QR code for parent access to {patientName}
                            </DialogDescription>
                        </div>
                    </div>
                </DialogHeader>

                <div className="py-6">
                    {loading ? (
                        <div className="flex flex-col items-center justify-center py-8">
                            <AiOutlineLoading3Quarters className="text-4xl text-emerald-500 animate-spin mb-3" />
                            <span className="text-gray-600">Generating parent access QR code...</span>
                        </div>
                    ) : error ? (
                        <div className="p-4 bg-red-50 border border-red-200 rounded-lg">
                            <div className="flex items-center gap-2 text-red-700 mb-3">
                                <FiAlertCircle />
                                <span className="text-sm font-medium">Error</span>
                            </div>
                            <p className="text-sm text-red-600 mb-3">{error}</p>
                            <Button
                                onClick={handleGenerate}
                                variant="outline"
                                size="sm"
                                className="w-full"
                            >
                                Try Again
                            </Button>
                        </div>
                    ) : generatedQR ? (
                        <div className="space-y-4">
                            {/* QR Code Display */}
                            <div className="flex flex-col items-center">
                                <div ref={qrRef}>
                                    <BrandedQRCode
                                        value={generatedQR.accessUrl}
                                        size={200}
                                        level="H"
                                        logoSize={45}
                                    />
                                </div>

                                {/* Info Badge */}
                                <div className="mt-4 flex items-center gap-2 text-sm text-gray-600">
                                    <FiCheckCircle className="text-emerald-500" />
                                    <span>Parent Access QR Generated</span>
                                </div>
                            </div>

                            {/* Details */}
                            <div className="bg-emerald-50 border border-emerald-200 rounded-lg p-4 space-y-2 text-sm">
                                <div className="flex justify-between">
                                    <span className="text-gray-600">Patient:</span>
                                    <span className="font-medium text-gray-900">{patientName}</span>
                                </div>
                                <div className="flex justify-between">
                                    <span className="text-gray-600">Valid Until:</span>
                                    <span className="font-medium text-gray-900">
                                        {formatExpiryDate(generatedQR.expiresAt)}
                                    </span>
                                </div>
                                <div className="flex justify-between">
                                    <span className="text-gray-600">Usage:</span>
                                    <span className="font-medium text-gray-900">One-time use</span>
                                </div>
                            </div>

                            {/* Instructions */}
                            <div className="bg-blue-50 border border-blue-200 rounded-lg p-3">
                                <p className="text-xs text-blue-800">
                                    <strong>Instructions:</strong> Share this QR code with the parent.
                                    When they scan it with their KEEPSAKE app, they will gain access
                                    to {patientName}'s medical records. The parent must have an existing
                                    KEEPSAKE account.
                                </p>
                            </div>

                            {/* Security Notice */}
                            <div className="bg-amber-50 border border-amber-200 rounded-lg p-3">
                                <p className="text-xs text-amber-800">
                                    <strong>Security:</strong> This QR code expires on{" "}
                                    {formatExpiryDate(generatedQR.expiresAt)} and can only be used once.
                                    Only share with verified parents or guardians of this patient.
                                </p>
                            </div>

                            {/* Action Buttons */}
                            <div className="flex gap-2">
                                <Button
                                    onClick={handleDownload}
                                    variant="default"
                                    className="flex-1 bg-emerald-600 hover:bg-emerald-700"
                                >
                                    <FiDownload className="mr-2" />
                                    Download
                                </Button>
                                <Button
                                    onClick={handleCopyUrl}
                                    variant="outline"
                                    className="flex-1"
                                >
                                    {copied ? (
                                        <>
                                            <FiCheckCircle className="mr-2 text-emerald-600" />
                                            Copied!
                                        </>
                                    ) : (
                                        <>
                                            <FiCopy className="mr-2" />
                                            Copy Link
                                        </>
                                    )}
                                </Button>
                            </div>
                        </div>
                    ) : null}
                </div>

                <div className="pt-4 border-t">
                    <Button
                        variant="outline"
                        onClick={onClose}
                        className="w-full"
                    >
                        Close
                    </Button>
                </div>
            </DialogContent>
        </Dialog>
    )
}

export default DoctorParentQRShareDialog
